### ISSUE TITLE
Support JS file？

### ISSUE THREAD

**Issue by Littlegolden** [circlecodesolution/vscode-ext-flutter-color-viewer#10]
I thought it supports any file, but there is no effect in the js file. Will you support js files?
![image](https://user-images.githubusercontent.com/35162802/109834667-67d99100-7c7d-11eb-9ed6-f1b672e80d8b.png)

**Comment by circlecodesolution** [comment]
Thank you for your valuable feedback.

Actually, we didn't plan to support all the languages, we initially planned only for a flutter, but now we have added support for all the languages and all file extension except for CSS, LESS, SCSS. We don't want to break the internal feature of the vscode, that's why we are not supporting these languages

You can now enjoy it in the js file
